const GET_ALL_APPLICATION_OF_APPLICANT_REQUEST = "GET_ALL_APPLICATION_OF_APPLICANT_REQUEST";
const GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS = "GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS";
const GET_ALL_APPLICATION_OF_APPLICANT_FAIL = "GET_ALL_APPLICATION_OF_APPLICANT_FAIL";


const GET_ALL_APPLICATION_ON_JOB_REQUEST = "GET_ALL_APPLICATION_ON_JOB_REQUEST";
const GET_ALL_APPLICATION_ON_JOB_SUCEESS = "GET_ALL_APPLICATION_ON_JOB_SUCEESS";
const GET_ALL_APPLICATION_ON_JOB_FAIL = "GET_ALL_APPLICATION_ON_JOB_FAIL";


const UPDATE_JOB_STATUS_REQUEST = "UPDATE_JOB_STATUS_REQUEST";
const UPDATE_JOB_STATUS_SUCEESS = "UPDATE_JOB_STATUS_SUCEESS";
const UPDATE_JOB_STATUS_FAIL = "UPDATE_JOB_STATUS_FAIL";
const UPDATE_JOB_STATUS_RESET = "UPDATE_JOB_STATUS_RESET";

const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
    GET_ALL_APPLICATION_OF_APPLICANT_REQUEST,
    GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS,
    GET_ALL_APPLICATION_OF_APPLICANT_FAIL,
    GET_ALL_APPLICATION_ON_JOB_REQUEST,
    GET_ALL_APPLICATION_ON_JOB_SUCEESS,
    GET_ALL_APPLICATION_ON_JOB_FAIL,
    UPDATE_JOB_STATUS_REQUEST,
    UPDATE_JOB_STATUS_SUCEESS,
    UPDATE_JOB_STATUS_FAIL,
    UPDATE_JOB_STATUS_RESET,
    CLEAR_ERRORS,
}