const GET_ALL_APPLICATION_OF_APPLICANT_REQUEST = "GET_ALL_APPLICATION_OF_APPLICANT_REQUEST";
const GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS = "GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS";
const GET_ALL_APPLICATION_OF_APPLICANT_FAIL = "GET_ALL_APPLICATION_OF_APPLICANT_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
    GET_ALL_APPLICATION_OF_APPLICANT_REQUEST,
    GET_ALL_APPLICATION_OF_APPLICANT_SUCEESS,
    GET_ALL_APPLICATION_OF_APPLICANT_FAIL,
    CLEAR_ERRORS,
}