const CREATE_NEW_COMPANY_REQUEST = "CREATE_NEW_COMPANY_REQUEST";
const CREATE_NEW_COMPANY_SUCEESS = "CREATE_NEW_COMPANY_SUCEESS";
const CREATE_NEW_COMPANY_FAIL = "CREATE_NEW_COMPANY_FAIL";
const CREATE_NEW_COMPANY_RESET = "CREATE_NEW_COMPANY_RESET";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    CREATE_NEW_COMPANY_REQUEST,
    CREATE_NEW_COMPANY_SUCEESS,
    CREATE_NEW_COMPANY_FAIL,
    CREATE_NEW_COMPANY_RESET,
    CLEAR_ERRORS,
};