const CREATE_NEW_COMPANY_REQUEST = "CREATE_NEW_COMPANY_REQUEST";
const CREATE_NEW_COMPANY_SUCEESS = "CREATE_NEW_COMPANY_SUCEESS";
const CREATE_NEW_COMPANY_FAIL = "CREATE_NEW_COMPANY_FAIL";
const CREATE_NEW_COMPANY_RESET = "CREATE_NEW_COMPANY_RESET";


const UPDATE_COMPANY_DETAILS_REQUEST = "UPDATE_COMPANY_DETAILS_REQUEST";
const UPDATE_COMPANY_DETAILS_SUCEESS = "UPDATE_COMPANY_DETAILS_SUCEESS";
const UPDATE_COMPANY_DETAILS_FAIL = "UPDATE_COMPANY_DETAILS_FAIL";
const UPDATE_COMPANY_DETAILS_RESET = "UPDATE_COMPANY_DETAILS_RESET";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    CREATE_NEW_COMPANY_REQUEST,
    CREATE_NEW_COMPANY_SUCEESS,
    CREATE_NEW_COMPANY_FAIL,
    CREATE_NEW_COMPANY_RESET,
    UPDATE_COMPANY_DETAILS_REQUEST,
    UPDATE_COMPANY_DETAILS_SUCEESS,
    UPDATE_COMPANY_DETAILS_FAIL,
    UPDATE_COMPANY_DETAILS_RESET,
    CLEAR_ERRORS,
};