const POST_NEW_JOB_REQUEST = "POST_NEW_JOB_REQUEST";
const POST_NEW_JOB_SUCEESS = "POST_NEW_JOB_SUCEESS";
const POST_NEW_JOB_FAIL = "POST_NEW_JOB_FAIL";
const POST_NEW_JOB_RESET = "POST_NEW_JOB_RESET";


const GET_ALL_JOB_PRESENT_ADMIN_REQUEST = "GET_ALL_JOB_PRESENT_ADMIN_REQUEST";
const GET_ALL_JOB_PRESENT_ADMIN_SUCEESS = "GET_ALL_JOB_PRESENT_ADMIN_SUCEESS";
const GET_ALL_JOB_PRESENT_ADMIN_FAIL = "GET_ALL_JOB_PRESENT_ADMIN_FAIL";



const SINGLE_JOB_DETAILS_REQUEST = "SINGLE_JOB_DETAILS_REQUEST";
const SINGLE_JOB_DETAILS_SUCEESS = "SINGLE_JOB_DETAILS_SUCEESS";
const SINGLE_JOB_DETAILS_FAIL = "SINGLE_JOB_DETAILS_FAIL";


const UPDATE_JOB_DETIALS_REQUEST = "UPDATE_JOB_DETIALS_REQUEST";
const UPDATE_JOB_DETIALS_SUCEESS = "UPDATE_JOB_DETIALS_SUCEESS";
const UPDATE_JOB_DETIALS_FAIL = "UPDATE_JOB_DETIALS_FAIL";
const UPDATE_JOB_DETIALS_RESET = "UPDATE_JOB_DETIALS_RESET";



const GET_ALL_JOB_REQUEST = "GET_ALL_JOB_REQUEST";
const GET_ALL_JOB_SUCEESS = "GET_ALL_JOB_SUCEESS";
const GET_ALL_JOB_FAIL = "GET_ALL_JOB_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    POST_NEW_JOB_REQUEST,
    POST_NEW_JOB_SUCEESS,
    POST_NEW_JOB_FAIL,
    POST_NEW_JOB_RESET,
    GET_ALL_JOB_PRESENT_ADMIN_REQUEST,
    GET_ALL_JOB_PRESENT_ADMIN_SUCEESS,
    GET_ALL_JOB_PRESENT_ADMIN_FAIL,
    SINGLE_JOB_DETAILS_REQUEST,
    SINGLE_JOB_DETAILS_SUCEESS,
    SINGLE_JOB_DETAILS_FAIL,
    UPDATE_JOB_DETIALS_REQUEST,
    UPDATE_JOB_DETIALS_SUCEESS,
    UPDATE_JOB_DETIALS_FAIL,
    UPDATE_JOB_DETIALS_RESET,
    GET_ALL_JOB_REQUEST,
    GET_ALL_JOB_SUCEESS,
    GET_ALL_JOB_FAIL,
    CLEAR_ERRORS
};