const POST_NEW_JOB_REQUEST = "POST_NEW_JOB_REQUEST";
const POST_NEW_JOB_SUCEESS = "POST_NEW_JOB_SUCEESS";
const POST_NEW_JOB_FAIL = "POST_NEW_JOB_FAIL";
const POST_NEW_JOB_RESET = "POST_NEW_JOB_RESET";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    POST_NEW_JOB_REQUEST,
    POST_NEW_JOB_SUCEESS,
    POST_NEW_JOB_FAIL,
    POST_NEW_JOB_RESET,
    CLEAR_ERRORS
};