const POST_NEW_JOB_REQUEST = "POST_NEW_JOB_REQUEST";
const POST_NEW_JOB_SUCEESS = "POST_NEW_JOB_SUCEESS";
const POST_NEW_JOB_FAIL = "POST_NEW_JOB_FAIL";
const POST_NEW_JOB_RESET = "POST_NEW_JOB_RESET";


const GET_ALL_JOB_PRESENT_ADMIN_REQUEST = "GET_ALL_JOB_PRESENT_ADMIN_REQUEST";
const GET_ALL_JOB_PRESENT_ADMIN_SUCEESS = "GET_ALL_JOB_PRESENT_ADMIN_SUCEESS";
const GET_ALL_JOB_PRESENT_ADMIN_FAIL = "GET_ALL_JOB_PRESENT_ADMIN_FAIL";


const CLEAR_ERRORS = "CLEAR_ERRORS";


export {
    POST_NEW_JOB_REQUEST,
    POST_NEW_JOB_SUCEESS,
    POST_NEW_JOB_FAIL,
    POST_NEW_JOB_RESET,
    GET_ALL_JOB_PRESENT_ADMIN_REQUEST,
    GET_ALL_JOB_PRESENT_ADMIN_SUCEESS,
    GET_ALL_JOB_PRESENT_ADMIN_FAIL,
    CLEAR_ERRORS
};