const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCEESS = "REGISTER_USER_SUCEESS";
const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

const CLEAR_ERRORS = " CLEAR_ERRORS";


export {
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCEESS,
    REGISTER_USER_FAIL,
    CLEAR_ERRORS
}